import { createPinia, setActivePinia } from 'pinia'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { ByteSource } from '@/core'
import { DerivedWorkClient } from '@/core'
import type { DerivedWorkWorkerLike } from '@/core'
import { BYTES_PER_ROW_PRESETS, COPY_BYTE_CAP, useDocumentStore } from '../document'

/** A hand-driven fake of the worker seam (mirrors `DerivedWorkClient.spec.ts`) —
 *  enough to construct a real `DerivedWorkClient` without a real `Worker`. */
class FakeWorker implements DerivedWorkWorkerLike {
  onmessage: ((event: MessageEvent) => void) | null = null
  terminateCalls = 0
  postMessage(): void {}
  terminate(): void {
    this.terminateCalls++
  }
}

function derivedWorkClient(): { client: DerivedWorkClient; worker: FakeWorker } {
  const worker = new FakeWorker()
  const client = new DerivedWorkClient(new File([], 'x.bin'), { createWorker: () => worker })
  return { client, worker }
}

/** A bytes-only stub — the store never reads, it only tracks identity and size. */
function sourceOfSize(size: number): ByteSource {
  return {
    size,
    read: () => Promise.resolve(new Uint8Array()),
    readSync: () => null,
    prefetch: () => {},
    close: () => {},
  }
}

/** Byte `i` holds `i & 0xff`, generated on demand — never allocated whole. */
function generated(offset: number, length: number, size: number): Uint8Array {
  const count = Math.max(0, Math.min(length, size - offset))
  const bytes = new Uint8Array(count)
  for (let i = 0; i < count; i++) {
    bytes[i] = (offset + i) & 0xff
  }
  return bytes
}

/**
 * A source that serves generated bytes through `read` and records every call, so
 * a test can prove the copy takes its bytes in one shot (a Direct read past the
 * cache threshold), never chunked. `readSync` always misses.
 */
class RecordingSource implements ByteSource {
  readonly reads: { offset: number; length: number }[] = []
  constructor(readonly size: number) {}
  read(offset: number, length: number): Promise<Uint8Array> {
    this.reads.push({ offset, length })
    return Promise.resolve(generated(offset, length, this.size))
  }
  readSync(): Uint8Array | null {
    return null
  }
  prefetch(): void {}
  close(): void {}
}

/**
 * A dead source: `read` always rejects, but `readSync` still answers for bytes
 * that were resident when it died — the emergent behaviour ADR-0004 leans on.
 */
class DeadButResidentSource implements ByteSource {
  constructor(
    readonly size: number,
    private readonly residentEnd: number,
  ) {}
  read(): Promise<Uint8Array> {
    return Promise.reject(new Error('source-gone'))
  }
  readSync(offset: number, length: number): Uint8Array | null {
    return offset + length <= this.residentEnd ? generated(offset, length, this.size) : null
  }
  prefetch(): void {}
  close(): void {}
}

beforeEach(() => {
  setActivePinia(createPinia())
})

describe('bytes-per-row presets (#19)', () => {
  it('offers 8 / 16 / 24 / 32, and every one is a multiple of 8', () => {
    expect([...BYTES_PER_ROW_PRESETS]).toEqual([8, 16, 24, 32])
    expect(BYTES_PER_ROW_PRESETS.every((n) => n % 8 === 0)).toBe(true)
  })

  it('defaults to 16', () => {
    expect(useDocumentStore().bytesPerRow).toBe(16)
  })

  it('setBytesPerRow switches to another preset', () => {
    const store = useDocumentStore()
    store.setBytesPerRow(24)
    expect(store.bytesPerRow).toBe(24)
    store.setBytesPerRow(8)
    expect(store.bytesPerRow).toBe(8)
  })

  it('ignores a value that is not one of the presets', () => {
    const store = useDocumentStore()
    for (const bad of [0, 10, 13, 20, 40, -16, Number.NaN]) {
      store.setBytesPerRow(bad)
      expect(store.bytesPerRow).toBe(16)
    }
  })

  it('leaves topByteOffset untouched — realigning it is the Viewport’s job (ADR-0006)', () => {
    const store = useDocumentStore()
    store.topByteOffset = 992
    store.setBytesPerRow(24)
    // The store only flips the preset; clampTopOffset runs from the metrics
    // watcher in HexViewer, exercised in the app-shell integration test.
    expect(store.topByteOffset).toBe(992)
  })
})

describe('the Selection: one range, byte-snapped (#22, ADR-0003)', () => {
  it('has no Selection until the reader first points at a byte', () => {
    expect(useDocumentStore().selection).toBeNull()
  })

  it('setCursor puts a collapsed Selection — the Cursor — on a byte', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(256), 'x.bin')
    store.setCursor(0x40)
    expect(store.selection).toEqual({ anchor: 0x40, focus: 0x40 })
  })

  it('a plain setCursor replaces the Selection — there is never more than one range', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(256), 'x.bin')
    store.extendSelectionTo(10)
    store.extendSelectionTo(30)
    expect(store.selection).toEqual({ anchor: 10, focus: 30 })
    store.setCursor(5)
    expect(store.selection).toEqual({ anchor: 5, focus: 5 })
  })

  it('extendSelectionTo moves the focus and keeps the anchor, direction preserved', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(256), 'x.bin')
    store.setCursor(20)
    store.extendSelectionTo(12)
    expect(store.selection).toEqual({ anchor: 20, focus: 12 })
    store.extendSelectionTo(8)
    expect(store.selection).toEqual({ anchor: 20, focus: 8 })
  })

  it('extendSelectionTo with no Selection yet anchors where it lands', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(256), 'x.bin')
    store.extendSelectionTo(50)
    expect(store.selection).toEqual({ anchor: 50, focus: 50 })
  })

  it('snaps an out-of-range offset to a real byte — never past the last one', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(64), 'x.bin')
    store.setCursor(999)
    expect(store.selection).toEqual({ anchor: 63, focus: 63 })
    store.setCursor(-4)
    expect(store.selection).toEqual({ anchor: 0, focus: 0 })
    store.setCursor(Number.NaN)
    expect(store.selection).toEqual({ anchor: 0, focus: 0 })
  })

  it('does nothing with no source open', () => {
    const store = useDocumentStore()
    store.setCursor(10)
    store.extendSelectionTo(20)
    expect(store.selection).toBeNull()
  })

  it('does nothing for a zero-byte file — there is no byte to point at', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(0), 'empty.bin')
    store.setCursor(0)
    expect(store.selection).toBeNull()
  })

  it('does not survive opening another document', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(256), 'a.bin')
    store.setCursor(0x30)
    expect(store.selection).not.toBeNull()
    store.open(sourceOfSize(256), 'b.bin')
    expect(store.selection).toBeNull()
  })
})

describe('copySelectionAsHex — the Selection out of the app as hex (#25)', () => {
  /** Select `[start, focus]` inclusive on a freshly opened source. */
  function selectRange(store: ReturnType<typeof useDocumentStore>, start: number, focus: number) {
    store.setCursor(start)
    store.extendSelectionTo(focus)
  }

  it('copies the Selection as a spaced-hex string and reports success', async () => {
    const store = useDocumentStore()
    store.open(new RecordingSource(1024), 'x.bin')
    selectRange(store, 4, 7) // bytes 04 05 06 07

    const written: string[] = []
    await store.copySelectionAsHex((text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual(['04 05 06 07'])
    expect(store.actionStatus).toEqual({
      ok: true,
      message: 'Copied 4 bytes to the clipboard as hex.',
    })
  })

  it('takes the bytes in one read — a Direct read, never chunked', async () => {
    const store = useDocumentStore()
    const source = new RecordingSource(64 * 1024 * 1024)
    store.open(source, 'big.bin')
    selectRange(store, 0, 4 * 1024 * 1024 - 1) // 4 MiB, well over the cache's 1 MiB threshold

    await store.copySelectionAsHex(() => Promise.resolve())

    expect(source.reads).toEqual([{ offset: 0, length: 4 * 1024 * 1024 }])
  })

  it('refuses past the 8 MiB cap, naming the cap and the Selection size, copying nothing', async () => {
    const store = useDocumentStore()
    store.open(new RecordingSource(64 * 1024 * 1024), 'big.bin')
    const bytes = COPY_BYTE_CAP + 512 * 1024 // 8.5 MiB
    selectRange(store, 0, bytes - 1)

    const written: string[] = []
    await store.copySelectionAsHex((text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual([]) // nothing reached the clipboard
    expect(store.actionStatus?.ok).toBe(false)
    expect(store.actionStatus?.message).toContain('8.0 MiB') // the cap
    expect(store.actionStatus?.message).toContain('8.5 MiB') // the Selection's size, human-readable
    expect(store.actionStatus?.message).toContain(bytes.toLocaleString()) // and exact
    expect(store.actionStatus?.message).toMatch(/nothing was copied/i)
  })

  it('marking a region past the cap is never itself blocked — only the copy is', () => {
    const store = useDocumentStore()
    store.open(new RecordingSource(64 * 1024 * 1024), 'big.bin')
    selectRange(store, 0, COPY_BYTE_CAP + 999999)

    expect(store.selection).toEqual({ anchor: 0, focus: COPY_BYTE_CAP + 999999 })
  })

  it('still copies a wholly-resident Selection after the source has died', async () => {
    const store = useDocumentStore()
    store.open(new DeadButResidentSource(4096, 64), 'dead.bin')
    selectRange(store, 0, 3) // inside the resident bytes

    const written: string[] = []
    await store.copySelectionAsHex((text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual(['00 01 02 03'])
    expect(store.actionStatus?.ok).toBe(true)
  })

  it('reports a read failure rather than copying a short or empty result', async () => {
    const store = useDocumentStore()
    store.open(new DeadButResidentSource(4096, 64), 'dead.bin')
    selectRange(store, 32, 200) // straddles the resident boundary — unreadable

    const written: string[] = []
    await store.copySelectionAsHex((text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual([])
    expect(store.actionStatus?.ok).toBe(false)
    expect(store.actionStatus?.message).toMatch(/could not be read/i)
  })

  it('does nothing with no source or no Selection', async () => {
    const store = useDocumentStore()
    const writeText = vi.fn(() => Promise.resolve())

    await store.copySelectionAsHex(writeText) // no source
    store.open(new RecordingSource(1024), 'x.bin')
    await store.copySelectionAsHex(writeText) // source, but no Selection

    expect(writeText).not.toHaveBeenCalled()
    expect(store.actionStatus).toBeNull()
  })

  it('clears the message when the Selection next moves', async () => {
    const store = useDocumentStore()
    store.open(new RecordingSource(1024), 'x.bin')
    selectRange(store, 0, 3)
    await store.copySelectionAsHex(() => Promise.resolve())
    expect(store.actionStatus).not.toBeNull()

    store.setCursor(10)
    expect(store.actionStatus).toBeNull()
  })

  it('clears the message when another document opens', async () => {
    const store = useDocumentStore()
    store.open(new RecordingSource(1024), 'x.bin')
    selectRange(store, 0, 3)
    await store.copySelectionAsHex(() => Promise.resolve())
    expect(store.actionStatus).not.toBeNull()

    store.open(new RecordingSource(1024), 'y.bin')
    expect(store.actionStatus).toBeNull()
  })

  /** A source whose `read` stays pending until the test resolves it. */
  function deferredSource(size: number): { source: ByteSource; resolve: () => void } {
    let resolve!: () => void
    const source: ByteSource = {
      size,
      read: (offset, length) =>
        new Promise((res) => {
          resolve = () => res(generated(offset, length, size))
        }),
      readSync: () => null,
      prefetch: () => {},
      close: () => {},
    }
    return {
      source,
      get resolve() {
        return resolve
      },
    }
  }

  it('drops a copy whose read resolves after the Selection has moved', async () => {
    const store = useDocumentStore()
    const deferred = deferredSource(1024)
    store.open(deferred.source, 'x.bin')
    selectRange(store, 0, 3)

    const written: string[] = []
    const done = store.copySelectionAsHex((text) => {
      written.push(text)
      return Promise.resolve()
    })

    store.setCursor(500) // the reader walks off while the read is still in flight
    deferred.resolve()
    await done

    expect(written).toEqual([]) // nothing copied for the abandoned range
    expect(store.actionStatus).toBeNull() // and no stale message
  })

  it('drops a copy whose read resolves after another document opened', async () => {
    const store = useDocumentStore()
    const deferred = deferredSource(1024)
    store.open(deferred.source, 'a.bin')
    selectRange(store, 0, 3)

    const written: string[] = []
    const done = store.copySelectionAsHex((text) => {
      written.push(text)
      return Promise.resolve()
    })

    store.open(new RecordingSource(1024), 'b.bin') // closes a.bin mid-read
    deferred.resolve()
    await done

    expect(written).toEqual([])
    expect(store.actionStatus).toBeNull()
  })
})

describe('copySelectionAsText — the Selection out of the app as raw text (#30)', () => {
  function selectRange(store: ReturnType<typeof useDocumentStore>, start: number, focus: number) {
    store.setCursor(start)
    store.extendSelectionTo(focus)
  }

  /** A source serving fixed bytes through `read`; `readSync` always misses. */
  function sourceOfBytes(bytes: number[]): ByteSource {
    const data = Uint8Array.from(bytes)
    return {
      size: data.length,
      read: (offset, length) => Promise.resolve(data.subarray(offset, offset + length)),
      readSync: () => null,
      prefetch: () => {},
      close: () => {},
    }
  }

  it('copies the Selection decoded as UTF-8 and reports success naming "text"', async () => {
    const store = useDocumentStore()
    // "café" — the é is the two bytes 0xC3 0xA9.
    store.open(sourceOfBytes([0x63, 0x61, 0x66, 0xc3, 0xa9, 0x21]), 's.bin')
    selectRange(store, 0, 4) // c a f é

    const written: string[] = []
    await store.copySelectionAsText((text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual(['café'])
    expect(store.actionStatus).toEqual({
      ok: true,
      message: 'Copied 5 bytes to the clipboard as text.',
    })
  })

  it('shares the 8 MiB cap and refusal with the hex copy — same message, nothing copied', async () => {
    const store = useDocumentStore()
    store.open(new RecordingSource(64 * 1024 * 1024), 'big.bin')
    const bytes = COPY_BYTE_CAP + 512 * 1024 // 8.5 MiB
    selectRange(store, 0, bytes - 1)

    const written: string[] = []
    await store.copySelectionAsText((text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual([])
    expect(store.actionStatus?.ok).toBe(false)
    expect(store.actionStatus?.message).toContain('8.0 MiB') // the cap
    expect(store.actionStatus?.message).toContain('8.5 MiB') // the Selection's size
    expect(store.actionStatus?.message).toMatch(/nothing was copied/i)
  })

  it('does nothing with no source or no Selection', async () => {
    const store = useDocumentStore()
    const writeText = vi.fn(() => Promise.resolve())

    await store.copySelectionAsText(writeText) // no source
    store.open(sourceOfBytes([1, 2, 3, 4]), 'x.bin')
    await store.copySelectionAsText(writeText) // source, but no Selection

    expect(writeText).not.toHaveBeenCalled()
    expect(store.actionStatus).toBeNull()
  })

  it('clears the message when the Selection next moves, same as the hex copy', async () => {
    const store = useDocumentStore()
    store.open(sourceOfBytes([0x41, 0x42, 0x43, 0x44]), 'x.bin')
    selectRange(store, 0, 3)
    await store.copySelectionAsText(() => Promise.resolve())
    expect(store.actionStatus).not.toBeNull()

    store.setCursor(2)
    expect(store.actionStatus).toBeNull()
  })
})

describe('copyInspectorValue — an Inspector row-value copy (#54, plan §3.6)', () => {
  it('writes the given text verbatim and reports success naming the row', async () => {
    const store = useDocumentStore()
    const written: string[] = []
    await store.copyInspectorValue('u32', '50462976', (text) => {
      written.push(text)
      return Promise.resolve()
    })

    expect(written).toEqual(['50462976'])
    expect(store.actionStatus).toEqual({ ok: true, message: 'Copied u32 value' })
  })

  it('does no rendering of its own — the Panel already formatted for hex / byte order', async () => {
    const store = useDocumentStore()
    const written: string[] = []
    await store.copyInspectorValue('i16', '0100', (text) => {
      written.push(text)
      return Promise.resolve()
    })
    expect(written).toEqual(['0100'])
  })

  it('reports a clipboard failure and writes no success message', async () => {
    const store = useDocumentStore()
    await store.copyInspectorValue('f64', '1', () => Promise.reject(new Error('denied')))

    expect(store.actionStatus?.ok).toBe(false)
    expect(store.actionStatus?.message).toMatch(/clipboard could not be written/i)
  })
})

describe('announceByteOrder — the byte-order flip message (#55, plan §4.3)', () => {
  it('sets the action-status slot with the spelled-out order', () => {
    const store = useDocumentStore()
    store.announceByteOrder('le')
    expect(store.actionStatus).toMatchObject({ ok: true, message: 'Byte order: little-endian' })
    store.announceByteOrder('be')
    expect(store.actionStatus).toMatchObject({ ok: true, message: 'Byte order: big-endian' })
  })

  it('is sticky — a Selection move does not clear it, only the next action (plan §4.4)', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(64), 'a.bin')
    store.setCursor(4)
    store.announceByteOrder('be')

    store.setCursor(8) // the copy path's clear does not touch a sticky message
    expect(store.actionStatus?.message).toBe('Byte order: big-endian')

    // The next copy replaces it, and that message *is* cleared on a later move.
    store.setCursor(12)
    store.extendSelectionTo(15)
    store.actionStatus = { ok: true, message: 'Copied 4 bytes to the clipboard as hex.' }
    store.setCursor(20)
    expect(store.actionStatus).toBeNull()
  })
})

describe('sourceHealth — the dead-source banner state (#26, ADR-0004)', () => {
  it('defaults to ok and resets to ok on open', () => {
    const store = useDocumentStore()
    expect(store.sourceHealth).toBe('ok')

    store.open(sourceOfSize(64), 'a.bin')
    store.setSourceHealth('failing')
    expect(store.sourceHealth).toBe('failing')

    store.open(sourceOfSize(64), 'b.bin')
    expect(store.sourceHealth).toBe('ok')
  })

  it('takes ok and failing transitions freely', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(64), 'a.bin')

    store.setSourceHealth('failing')
    expect(store.sourceHealth).toBe('failing')
    store.setSourceHealth('ok')
    expect(store.sourceHealth).toBe('ok')
  })

  it('latches gone: neither a later read-failed escalation nor a stray success can move away from it, only open', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(64), 'a.bin')

    store.setSourceHealth('gone')
    expect(store.sourceHealth).toBe('gone')

    // A read-failed rejection settling after the one that latched — e.g. a
    // different row's fetch, in the same batch, resolving in a different
    // order — must not downgrade the banner to the escalation wording.
    store.setSourceHealth('failing')
    expect(store.sourceHealth).toBe('gone')

    // Nor can a stray success dismiss it entirely.
    store.setSourceHealth('ok')
    expect(store.sourceHealth).toBe('gone')

    // Only opening a new document resets it.
    store.open(sourceOfSize(64), 'b.bin')
    expect(store.sourceHealth).toBe('ok')
  })
})

describe('requestReveal — the Bitmap click-to-cursor reveal signal (plan §4.9)', () => {
  it('is null until a reveal is asked for', () => {
    expect(useDocumentStore().revealRequest).toBeNull()
  })

  it('carries the (byte-clamped) offset in a fresh object each call — a repeat is still a distinct trigger', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(4096), 'a.bin')

    store.requestReveal(1000)
    expect(store.revealRequest).toEqual({ offset: 1000 })
    const first = store.revealRequest

    store.requestReveal(1000)
    expect(store.revealRequest).toEqual({ offset: 1000 })
    expect(store.revealRequest).not.toBe(first) // a new reference, so the watcher re-fires

    store.requestReveal(999_999) // clamped to the last real byte
    expect(store.revealRequest!.offset).toBe(4095)
  })

  it('is inert with no document open, and resets when one opens', () => {
    const store = useDocumentStore()
    store.requestReveal(10)
    expect(store.revealRequest).toBeNull()

    store.open(sourceOfSize(4096), 'a.bin')
    store.requestReveal(10)
    expect(store.revealRequest).not.toBeNull()

    store.open(sourceOfSize(2048), 'b.bin')
    expect(store.revealRequest).toBeNull()
  })
})

describe('derivedWorkClient — the worker-crossing lifecycle (#103, ADR-0013)', () => {
  it('is null until a document opens with one', () => {
    expect(useDocumentStore().derivedWorkClient).toBeNull()
  })

  it('open with no third argument leaves it null — every existing call site is unaffected', () => {
    const store = useDocumentStore()
    store.open(sourceOfSize(64), 'a.bin')
    expect(store.derivedWorkClient).toBeNull()
  })

  it('holds the client a caller passes to open', () => {
    const store = useDocumentStore()
    const { client } = derivedWorkClient()
    store.open(sourceOfSize(64), 'a.bin', client)
    expect(store.derivedWorkClient).toBe(client)
  })

  it('terminates the previous document’s client when the next document opens — one worker per open document', () => {
    const store = useDocumentStore()
    const first = derivedWorkClient()
    const second = derivedWorkClient()
    store.open(sourceOfSize(64), 'a.bin', first.client)

    store.open(sourceOfSize(64), 'b.bin', second.client)

    expect(first.worker.terminateCalls).toBe(1)
    expect(store.derivedWorkClient).toBe(second.client)
  })

  it('opening a plain document (no client) still terminates the previous one', () => {
    const store = useDocumentStore()
    const first = derivedWorkClient()
    store.open(sourceOfSize(64), 'a.bin', first.client)

    store.open(sourceOfSize(64), 'b.bin')

    expect(first.worker.terminateCalls).toBe(1)
    expect(store.derivedWorkClient).toBeNull()
  })
})
